# Generated by Django 4.1.5 on 2023-01-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="candidateInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "schoolYear",
                    models.CharField(
                        choices=[
                            ("F", "Freshman"),
                            ("S", "Sophomore"),
                            ("J", "Junior"),
                            ("S", "Senior"),
                            ("G", "Graduate"),
                        ],
                        max_length=1,
                    ),
                ),
                ("major", models.CharField(max_length=50)),
                ("skills", models.JSONField()),
                ("experiences", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(name="Item",),
    ]
