# Generated by Django 4.1.5 on 2023-02-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_candidateinfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateinfo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
